### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by antoKeinanen** [erikpeik/ot-harjoitustyo#1]
Testattu 16.04.2025 10.45 asennetulla versiolla. Commit hash: [8af0c0b](https://github.com/erikpeik/ot-harjoitustyo/tree/8af0c0b45d9c4d86f400fd5d5b115c364b359782)

Projekti näyttää olevan todella hyvällä mallilla. Koodi on suurimmaksiosaksi hyvin kirjoitettua ja luettavaa. Suurimmat ongelmat, mitä löysin ovat lähinnä koodin luettavuuteen vaikuttavia,  eli mistään isosta ei todellakaan ole kyse. Hyvää työtä, jatka samaan malliin!

## Korjausehdoukset
- [button.py:34-41](https://github.com/erikpeik/ot-harjoitustyo/blob/8af0c0b45d9c4d86f400fd5d5b115c364b359782/minesweeper/src/ui/button.py#L34-L41) Yksinkertaista `return x >= self.pos[0] and x <= self.pos[0] + self.width and y >= self.pos[1] and y <= self.pos[1] + self.height`
- [tile.py:19-38](https://github.com/erikpeik/ot-harjoitustyo/blob/8af0c0b45d9c4d86f400fd5d5b115c364b359782/minesweeper/src/ui/tile.py#L19-L38), Eriytä erilliseen `_get_tile_coordinates(...) -> tuple` funktioon ja käytä [guard rakennetta](https://en.wikipedia.org/wiki/Guard_(computer_science))
- [tile.py:55-67](https://github.com/erikpeik/ot-harjoitustyo/blob/8af0c0b45d9c4d86f400fd5d5b115c364b359782/minesweeper/src/ui/tile.py#L55-L67) Käytä guard rakennetta
- [ui.py:37-59](https://github.com/erikpeik/ot-harjoitustyo/blob/8af0c0b45d9c4d86f400fd5d5b115c364b359782/minesweeper/src/ui/ui.py#L37-L59) Tässäkin voisi käyttää guard rakennetta, mutta `return` sijasta `continue` ja `break`
- [minesweeper_test.py:10-13](https://github.com/erikpeik/ot-harjoitustyo/blob/8af0c0b45d9c4d86f400fd5d5b115c364b359782/minesweeper/src/tests/logic/minesweeper_test.py#L10-L13) Vähän turhan oloinen testi.

## Koodin ajaminen
En pystynyt asentamaan projektin riippuvuuksia yliopiston virtuaalityöasemalla. Tämä johtui virheellisestä `pyproject.toml` tiedostosta. Korjattu tiedosto:
```toml
[tool.poetry]
name = "minesweeper"
version = "0.1.0"
description = ""
authors = ["Erik-Peik Mende <erik-peik.mende@helsinki.fi>" ]

[tool.poetry.dependencies]
python = "^3.10"
pygame = "^2.6.1"
invoke = "^2.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
pylint = "^3.3.5"
pytest = "^8.3.5"
coverage = "^7.8.0"
autopep8 = "^2.3.2"
```
